version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: finfraudguard_app
    ports:
      - "8000:8000"   
    env_file:
      - .env
    volumes:
      - ./:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  neo4j:
    image: neo4j:5
    container_name: neo4j_db
    ports:
      - "7687:7687"
      - "7474:7474"
    environment:
      - NEO4J_AUTH=neo4j/your_neo4j_password
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:
